lsst/obs_decam

- policy/DecamMapper.paf
Changes to fix the problem of not looping over ccdnum
> Modify levels in DecamMapper.paf

- config/ingestCalibs.py
- policy/DecamMapper.paf
- python/lsst/obs/decam/decamMapper.py
- python/lsst/obs/decam/ingest.py
- python/lsst/obs/decam/ingestCalibs.py
- tests/getRaw.py
Goals:
* Have something to ingest calibration data and create a calibration registry (calibRegistry.sqlite3)
* Add mapping class calibration into DecamMapper and make butler able to get bias/flat/fringe.
* Include calib in testdata_decam and add to the unit test retrieving calib data.
> DM-3766: Add Butler access to calibration data in obs_decam

- python/lsst/obs/decam/decamMapper.py
- tests/testWcsCards.py
workaround before the official TPV support.
> Remove wcs keywords from the raw metadata

- tests/getRaw.py
- tests/testProcessCcd.py
- tests/testWcsCards.py
> Tickets/DM-4916 Add a test to run processCcd with testdata_decam

- tests/getRaw.py
Update mapper name test to new Butler.getMapperClass
Butler objects no longer directly expose a .mapper attribute.
as of DM-4683.  This change broke the package name test.
Test now use the class static method getMapperClass.
> DM-5372: Fix obs_* packages and ci tests broken by DM-4683

- python/lsst/obs/decam/decamMapper.py
regarding the steps in the readme.md for this package,
now processCcdDecam.py can be run without the registry.sqlite file.
HOWEVER for this script, the data must still be imported (step 3,
ingestImagesDecam.py) because this creates files (aliases, actually)
that conform to the template in the policy file. The registry free
butler depends on this correlation between file names and template.
> adds registry-free butler support

- config/coaddDriver.py
- config/mergeCoaddDetections.py
- config/mergeCoaddMeasurements.py
- config/multiBandDriver.py
- policy/DecamMapper.paf
for running forcedPhotCcd, coaddDriverTask, and multiBandDriverTask
> DM-5633: Add config and data products

- python/lsst/obs/decam/decamMapper.py
- tests/testGetInstcal.py
- tests/testGetRaw.py
This avoids duplication of conflicting WCS keywords.
> Strip WCS keys from metadata of instcals.

- tests/testGetRaw.py
@ctslater noticed that I'd re-added these lines during a rebase. They're all in the dict now, so unneeded.
> Remove unneeded lines from bad rebase.

- policy/DecamMapper.paf
- python/lsst/obs/decam/decamMapper.py
- python/lsst/obs/decam/ingest.py
- tests/testGetInstcal.py
Since an HDU's position in an instcal file does not necessarily correspond to
its CCD number, this template had been mislabling CCDs.
Also removes special handling of decam raw files that was required to track the
hdu field. This code was largely a duplication of the pipe_tasks ingest task,
and can be alleviated with the minor changes to that task (also implemented on
this ticket.)
> Use HDU in instcal templates instead of ccdnum.

- python/lsst/obs/decam/ingestCalibs.py
Use NONE for CP bias, no matter what FILTER header says, so to get
around wrong validity fix with misleading filter headers in bias.
> DM-9113: the bias ingestion should not care about the filter

- tests/testGetInstcal.py
- tests/testGetRaw.py
Changes are on afw, this is a fix to a now-incorrect test
> We now obey INHERIT, so PROPOSER should be seen

- tests/getIdRepo/repositoryCfg.yaml
- tests/testGetId.py
This test was failing because of a sequence of
events:
The test was passing into Butler init an
instantiated mapper passed in but not comparing
equal with the mapper loaded by the repository
cfg.
A repositoryCfg.yaml was being created by the old
use of the Butler API (because the old API creates
a read-write output repository), and it was not
geting cleaned up by the test.
When the test runs again on the same computer
where the old repositoryCfg.yaml file exists, the
mapper is reinstantiated as described by the
repositoryCfg file.
The passed-in instantiated mapper and the
reinstantiated mapper do not compare equal,
becuase they do not implement the __eq__ method
and they are not the same instance.
Butler interprets this as the mapper from the cfg
and the passed-in mapper do not match, and …
> obs_decam - modernize Butler API use in testGetId

- python/lsst/obs/decam/makeDecamRawVisitInfo.py
- tests/test_getRaw.py
Some decam metadata has the pressure set to 1 atmosphere, which is not correct. It needs to be close to correct in order to calculate the right amount of refraction for an observation.
> DM-13096: Ensure Weather metadata is within valid range.

- policy/DecamMapper.yaml
This PR registers a dataset mapping for metadata persisted by `ApPipeTask`. The config dataset is delegated to `obs_base`.
> DM-13163: Refactor ap_pipe to use CmdLineTask primitives

- config/datasetIngest.py
This PR adds an observatory override file for `lsst.ap.verify.DatasetIngestTask` to `obs_decam`.
> DM-13530: Generalize ingestion to non-HiTS data

- README.md
- python/lsst/obs/decam/ingest.py
This PR replaces all use of `DecamIngestTask`'s default `--filetype` argument with an explicit one (preserving behavior), then changes the default of `--filetype`.
> DM-14237: Change DecamIngestTask --filetype default from instcal to raw

- config/apPipe.py
- config/association.py
- config/datasetIngest.py
This PR adds DECam-specific settings for `ApPipeTask` and `AssociationTask` to obs package override files.
> DM-12315: Generalize ap_pipe to non-HiTS data

- config/isr.py
- config/processCcd.py
- config/processCcdCpIsr.py
- config/runIsr.py
- config/runIsrCp.py
This ticket adds a stand-alone runIsr.py script, as well as ensuring that runIsr.py and processCcd.py read the same ISR configuration files.
> DM-6640: IsrTask is not a valid CmdLineTask

- python/lsst/obs/decam/decamMapper.py
- tests/test_getInstcal.py
- tests/test_getRaw.py
This also cleans up a bit of unnecessary code looking in HDU0 for the dark time,
and what looks like a slightly messed up rebase in test_getRaw.py.
> DM-16593: Decam VisitInfo ExposureId set incorrectly

- policy/DecamMapper.yaml
- tests/test_crosstalk.py
Previously, masking and interpolation was done on a by-defect-type
basis: a set of bad pixels were masked and interpolated, then the
process repeated on different bad pixels. However, this ignores the
case where different types of bad pixels may be contiguous, resulting
in interpolated pixels being derived based on previously interpolated
values.
After reordering, unit test check values are slightly different.
> DM-19382: Update test value for interpolation changes.

- policy/DecamMapper.yaml
This PR defines the DECam location for the `apdb_marker` dataset introduced in lsst/obs_base#182.
> DM-21877: Create "marker" Butler dataset for PPDB

- README.md
- config/apPipe.py
- config/calibrate.py
- config/characterizeImage.py
- config/isr.py
- config/processCcd.py
- config/processCcdCpIsr.py
- python/lsst/obs/decam/crosstalk.py
- tests/nopytest_test_processCcd.py
This PR changes `obs_decam` configuration files to be appropriate for Gen 3. It also performs some general cleanup inspired by discussion on `#dm-alert-prod`.
> DM-23616: Run converted ap_verify testdata through gen3 pipeline

- config/coaddDriver.py
- config/datasetIngest.py
- config/multiBandDriver.py
- config/runIsr.py
- config/runIsrCp.py
- config/singleFrameDriver.py
See https://community.lsst.org/t/pex-config-configs-now-know-where-they-are/4023.
> DM-24495: Switch to using __file__ to reference other configs.

- config/isr.py
This PR removes all references to the `IsrConfig.doAddDistortionModel` field, which is no longer  used by `IsrTask`.
> DM-23651: ap_pipe calls some deprecated things

- .gitignore
- config/ingestCuratedCalibs.py
- config/isr.py
- decam/SConscript
- decam/makeCrosstalkDecam.py
- pipelines/RunIsr.yaml
- policy/DecamMapper.yaml
- python/lsst/obs/decam/crosstalk.py
- python/lsst/obs/decam/decamMapper.py
Handle crosstalk via a CrosstalkCalibs persisted as FITS/YAML.  Use ip_isr's updated CrosstalkTask for application, even for inter-ccd crosstalk.  obs_decam still needs to subclass CrosstalkTask to implement the prepCrosstalk() method with gen2 butlers.
> DM-23983: Cannot apply crosstalk in Gen 3 DECam processing

- python/lsst/obs/decam/ingest.py
- python/lsst/obs/decam/ingestCalibs.py
- tests/test_parseCalibsGen2.py
This PR enables obs_decam to ingest both CP (community pipeline) calibs and stack-built calibs. Previously we were only supporting CP calibs because nobody had built DECam master calibs with the stack before. I have now successfully constructed biases and (g-band) flats and ingested them.
> DM-17538: Generate stack-produced (rather than CP) calibration products for DECam

- python/lsst/obs/decam/_instrument.py
It can take quite a long time to read the camera definition
from disk.
> DM-26317: Add lru cache to Instrument.getCamera

- config/bias.py
- config/dark.py
- config/flat.py
- config/fringe.py
The config settings set in `config/isr.py` were used correctly in `processCcd.py`, but were not used for `constructBias.py` or `constructFlat.py`. This was not a problem for processing that used the Decam community pipeline calibrations, but resulted in the incorrect processing of the master bias in particular.
The defaults in `config/isr.py` also turn on and apply settings that are incorrect for constructing the master bias or flat, so I explicitly disabled these in a separate commit.
> Tickets/DM-26554: Use decam ISR configs for bias and flat construction

- tests/test_getInstcal.py
- tests/test_getRaw.py
End usage of FilterProperty, as per RFC-730.
> DM-27168: Phase out use of FilterProperty

- config/ingestCuratedCalibs.py
- decam/makeLinearizer.py
Create gen3 linearizers.
This involves wrapping the gen2 table data in the calibration class.
> DM-23985: Cannot do linearity corrections in Gen 3 DECam processing

- pipelines/DRP.yaml
- pipelines/RunIsr.yaml
- pipelines/RunIsrForCrosstalkSources.yaml
- pipelines/RunIsrWithCrosstalk.yaml
Add updated two-part crosstalk ISR pipeline definitions.
> DM-27833: Enable gen3 inter-chip crosstalk for DECam

- python/lsst/obs/decam/_instrument.py
- tests/test_instrument.py
This PR adds filter alias handling to DECam's Gen 2 to Gen 3 conversion code. In particular, this allows both `y` and `Y` to be recognized as filter names.
> DM-28439: Converting HiTS2015 repo fails on bad filter

- pipelines/DRP.yaml
until a generic Object.yaml is written.
> DM-22277: Exclude objectTable subset from DRP pipeline

- config/calibrate.py
- config/characterizeImage.py
- config/measureCoaddSources.py
- python/lsst/obs/decam/decamFilters.py
Original community PR: https://github.com/lsst/obs_decam/pull/199
There are two new narrow-/medium-band filters installed on DECam: an N419 narrow-band filter and an N540 medium-band filter. The N540 filter is used by the Merian survey, which depends on the science pipelines for data reduction.
- added the FilterDefinition of both filters to decamFilters.py.
- assigned the PS-1 g-band as the reference filter for both of them in `config/calibrate.py`, `config/characterizeImage.py`, and `config/measureCoaddSources.py`.
- added missing reference filter information for the N964 filter which has already been registered, assigning it to the z-band in the above three files.
> DM-31783: Register the new N419 and N540 filters

- tests/test_getInstcal.py
- tests/test_getRaw.py
This PR removes uses of `VisitInfo.getExposureId()`, which was deprecated in lsst/afw#614.
> DM-13943: Deprecate VisitInfo.getExposureId()

- decam/makeLinearizer.py
Two new parameters were added to ip/isr/linearize.py, that necessitated this change.
> DM-33297: Add correction of systematic photodiode error

- config/SkyBotEphemerisQuery.py
This PR adds an instrument-level config override file for `lsst.ap.association.skyBotEphemerisQuery.SkyBotEphemerisQueryTask`. I'm fairly confident that these values are appropriate for all DECam data sets and for all pipelines.
> DM-34693: add instrument config for SkyBotEphemerisQueryTask

- config/isr.py
- tests/config/isr.py
Switch config file to use current overscan config options instead of deprecated isrTask config options.
> DM-33429: Add ability to do both serial and parallel overscan correction

- tests/test_isr.py
> DM-32940: Remove unnecessary test for butler dataset existence

- SConstruct
- pipelines/DRP.yaml
- pipelines/README.md
Pipelines should go in *_pipe packages.
> DM-35579: Remove pipelines forwarding stubs.

- doc/lsst.obs.decam/using-obs-decam.rst
I've requested 2 reviewers because it's relevant to each of you and I'm nervous without Jenkins, even though this is just a documentation change.
> DM-40230: Remove Note about the resolved DM-30651.

- config/characterizeImage.py
The config fields were removed because they had deprecations in place for over a year, and were deprecated because they never did anything in the first place.
> DM-34769: Remove characterizeImage refObjLoader

- tests/test_ingest.py
This should have happened long ago, on DM-31924.  I found it here by accidentally being overzealous about which deprecation warnings I temporarily turned into errors in daf_butler.
> DM-34340: Convert deprecated dimension packer usage.

- tests/test_isr.py
The 'root' argument never existed, but until DM-40441 this method seems to have accidentally accepted (and ignored) arbitrary kwargs.
> DM-40441: Drop unnecessary argument to SimplePipelineExecutor.from_pipeline.

- config/mpSkyEphemerisQuery.py
Just adding mpSkyEphemerisQuery overrides: observatory code W84 and a buffer of 0.2 degrees for the search cone.
> DM-42576: mpSkyEphemerisQuery config overrides
